config/routes.rb
Rails.application.routes.draw do
  resources :search_images
  get 'categories/index'

  get 'category/index'

  get 'take-test/:id', to:'take_test#index'
  post 'take-test/:id', to:'take_test#create'
  
  get 'joiners/new'

  # get 'joiners/edit'
  get 'joiners/delete'
  get ':id/review_freelancers/new', to: 'review_freelancers#new'
  post ':id/review_freelancers', to: 'review_freelancers#create'

  #  get 'works', to: 'works#index'
  #  get '/works/new', to: 'works#new'
  #  post '/works/new', to: 'works#create'
  #  delete '/works/delete', to: 'works#destroy'
  #  get 'works/edit'
  
  get 'search_works/index'
  get 'search_works', to: 'search_works#index'
  post 'search_works', to: 'search_works#advance'
  
  get 'sessions/new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  root 'static_pages#home'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  get '/edit/:id', to: 'users#edit'
  resources :users
  resources :works
  resources :joiners
  resources :categories
  resources :review_freelancers
#  resources :take
end

app/models/search_image.rb
class SearchImage < ApplicationRecord
end

app/controllers/search_images_controller.rb
class SearchImagesController < ApplicationController
  before_action :set_search_image, only: [:show, :edit, :update, :destroy]

  # GET /search_images
  # GET /search_images.json
  def index
    @search_images = SearchImage.all
  end

  # GET /search_images/1
  # GET /search_images/1.json
  def show
  end

  # GET /search_images/new
  def new
    @search_image = SearchImage.new
  end

  # GET /search_images/1/edit
  def edit
  end

  # POST /search_images
  # POST /search_images.json
  def create
    @search_image = SearchImage.new(search_image_params)

    respond_to do |format|
      if @search_image.save
        format.html { redirect_to @search_image, notice: 'Search image was successfully created.' }
        format.json { render :show, status: :created, location: @search_image }
      else
        format.html { render :new }
        format.json { render json: @search_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_images/1
  # PATCH/PUT /search_images/1.json
  def update
    respond_to do |format|
      if @search_image.update(search_image_params)
        format.html { redirect_to @search_image, notice: 'Search image was successfully updated.' }
        format.json { render :show, status: :ok, location: @search_image }
      else
        format.html { render :edit }
        format.json { render json: @search_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_images/1
  # DELETE /search_images/1.json
  def destroy
    @search_image.destroy
    respond_to do |format|
      format.html { redirect_to search_images_url, notice: 'Search image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search_image
      @search_image = SearchImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_image_params
      params.fetch(:search_image, {})
    end
end

app/helpers/search_images_helper.rb
module SearchImagesHelper
end

app/views/search_images/_form.html.erb
<%= form_for(search_image) do |f| %>
  <% if search_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search_image.errors.count, "error") %> prohibited this search_image from being saved:</h2>

      <ul>
      <% search_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/search_images/edit.html.erb
<h1>Editing Search Image</h1>

<%= render 'form', search_image: @search_image %>

<%= link_to 'Show', @search_image %> |
<%= link_to 'Back', search_images_path %>

app/views/search_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search Images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @search_images.each do |search_image| %>
      <tr>
        <td><%= link_to 'Show', search_image %></td>
        <td><%= link_to 'Edit', edit_search_image_path(search_image) %></td>
        <td><%= link_to 'Destroy', search_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search Image', new_search_image_path %>

app/views/search_images/new.html.erb
<h1>New Search Image</h1>

<%= render 'form', search_image: @search_image %>

<%= link_to 'Back', search_images_path %>

app/views/search_images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_search_image_path(@search_image) %> |
<%= link_to 'Back', search_images_path %>