config/routes.rb
Rails.application.routes.draw do
  resources :search_images
  get 'categories/index'

  get 'category/index'

  get 'take-test/:id', to:'take_test#index'
  post 'take-test/:id', to:'take_test#create'
  
  get 'joiners/new'

  # get 'joiners/edit'
  get 'joiners/delete'
  get ':id/review_freelancers/new', to: 'review_freelancers#new'
  post ':id/review_freelancers', to: 'review_freelancers#create'

  #  get 'works', to: 'works#index'
  #  get '/works/new', to: 'works#new'
  #  post '/works/new', to: 'works#create'
  #  delete '/works/delete', to: 'works#destroy'
  #  get 'works/edit'
  
  get 'search_works/index'
  get 'search_works', to: 'search_works#index'
  post 'search_works', to: 'search_works#advance'
  
  get 'sessions/new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  root 'static_pages#home'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  get '/edit/:id', to: 'users#edit'
  resources :users
  resources :works
  resources :joiners
  resources :categories
  resources :review_freelancers
#  resources :take
end

app/models/user.rb
class User < ApplicationRecord

  has_many :works, dependent: :destroy
  belongs_to :role
  has_many :freelancer_categories
  has_many :categories, through: :freelancer_categories
  has_many :joiners

#  accepts_nested_attributes_for  :freelancer_categories
  before_save { email.downcase! }
  validates :username,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, presence: true, allow_blank: true, on: :update

   def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
end

app/controllers/search_works_controller.rb
class SearchWorksController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :advance

  def index
    @user = current_user
    if @user.nil?
      flash[:danger] = "Please login"
      redirect_to login_path
    else
      if @user[:role_id] == 1
        @categories = Category.joins(:freelancer_categories).where(freelancer_categories:{user_id: @user[:id]})
        @works = Work.joins(:categories, :user).left_outer_joins(:joiners).where(status:[0, 4], categories:{id: @categories}).distinct
        @works = @works.sort do |a, b|
          case
          when check_not_match(@categories, a.categories) < check_not_match(@categories, b.categories)
            -1
          when check_not_match(@categories, a.categories) > check_not_match(@categories, b.categories)
            1
          else
            case
            when check_match(@categories, a.categories) < check_match(@categories, b.categories) 
              1
            when check_match(@categories, a.categories) > check_match(@categories, b.categories)
              -1
            else
              a.status <=> b.status
            end
          end
        end
        #        @work = sort_work(@works, @categories)
      else
        flash[:danger] = "You don't have permission"
        redirect_to @user
      end
    end
  end
  
  def advance
    @user = current_user
    if @user.nil?
      flash[:danger] = "Please login"
      redirect_to login_path
    else
      if @user[:role_id] == 1
        if !params[:category_ids].nil?
          @categories = Category.joins(:freelancer_categories).where(freelancer_categories:{user_id: @user[:id]})
          @works = Work.joins(:categories, :user).where(status:[0, 4], categories:{id: params[:category_ids]}).distinct
          @works = @works.sort do |a, b|
            case
            when check_not_match(@categories, a.categories) < check_not_match(@categories, b.categories)
              -1
            when check_not_match(@categories, a.categories) > check_not_match(@categories, b.categories)
              1
            else
              case
              when check_match(@categories, a.categories) < check_match(@categories, b.categories) 
                1
              when check_match(@categories, a.categories) > check_match(@categories, b.categories)
                -1
              else
                a.status <=> b.status
              end
            end
          end
          #          @work = sort_work(@works, @categories)
        else
          @categories = Category.joins(:freelancer_categories).where(freelancer_categories:{user_id: @user[:id]})
          @works = Work.joins(:categories, :user).where(status:[0, 4], categories:{id: @categories}).distinct
          @works = @works.sort do |a, b|
            case
            when check_not_match(@categories, a.categories) < check_not_match(@categories, b.categories)
              -1
            when check_not_match(@categories, a.categories) > check_not_match(@categories, b.categories)
              1
            else
              case
              when check_match(@categories, a.categories) < check_match(@categories, b.categories) 
                1
              when check_match(@categories, a.categories) > check_match(@categories, b.categories)
                -1
              else
                a.status <=> b.status
              end
            end
          end
          #          @work = sort_work(@works, @categories)
        end
        render '_list_works', layout: false
      else
        flash[:danger] = "You don't have permission"
        redirect_to @user
      end
    end
  end
  
  def check_match(user_categories, work_categories)
    count = 0
    work_categories.each {
      |category| if check_exist(category, user_categories)
        count = count +1
      end
    }
    return count
  end
  
  def check_not_match(user_categories, work_categories)
    count = 0
    work_categories.each {|category|
      if !check_exist(category, user_categories)
        count = count +1
      end
    }
    return count
  end
  
  def check_exist(category, user_categories)
    check =  false
    user_categories.each { |user_category| 
      if user_category["id"] == category["id"]
        check = true
        break
      end
    }
    return check
  end
  
  #  def sort_work(work, categories)
  #    work = work.sort do |a, b|
  #      case
  #      when check_not_match(categories, a.categories) < check_not_match(categories, b.categories)
  #        -1
  #      when check_not_match(categories, a.categories) > check_not_match(categories, b.categories)
  #        1
  #      else
  #        case
  #        when check_match(categories, a.categories) < check_match(categories, b.categories) 
  #          1
  #        when check_match(categories, a.categories) > check_match(categories, b.categories)
  #          -1
  #        else
  #          a.status <=> b.status
  #        end
  #      end
  #    end
  #  end
end

app/helpers/search_works_helper.rb
module SearchWorksHelper
end

app/views/search_works/_list_works.html.erb
<center>
    <h2>List works</h2>
</center>
<table class="table table-hover table-border">
    <thead>
        <tr>
            <th>#</th>
            <th>Customer</th>
            <th>Work name</th>
            <th>Skill</th>
            <th>Price</th>
            <th>Work's status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <% if !@works.nil?%>
          <%  @works.each_with_index do |work, index| %> 
            <tr>
                <td><%= index+1 %> </td>
                <td><%= work.user.fullname%> </td>
                <td><%= work.name %></td>
                <td>
                    <% work.categories.each do |category| %>
                      <% if @categories.include? category  %>
                        <%=  link_to category.name, 'javascript:;',class: "btn btn-primary" %>
                        <% else %>
                          <%=  link_to category.name, 'javascript:;', class: "btn btn-danger" %>
                          <%  end %>
                        <% end %>
                    </td>
                    <td><%= work.price %> $</td>
                    <td>
                        <%if work.status == 0%>
                          Waiting
                        <%else%>
                          Delay
                        <%end%>
                    </td>
                    <td>
                        <%= link_to 'View detail', work_path(work), class: "btn btn-default"  %>
                      </td>
                  </tr>
                <% end
                else
              %>
              <%  end%>
          </tbody>
      </table>

app/views/search_works/index.html.erb
<%= form_tag(search_works_path, :method => "post", remote: true) do %>
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 
  <% @categories.each do |category| %>
    <%= category.name %>
    <%= check_box_tag 'category_ids[]', category.id, class: 'form-control' %>
    <% end %>
    <%#= submit_tag "Search" %>
  <% end %>

  <hr/>
  <div id="results">
      <center>
          <h2>List works</h2>
      </center>
      <table class="table table-hover table-border">
          <thead>
              <tr>
                  <th>#</th>
                  <th>Customer</th>
                  <th>Work name</th>
                  <th>Skill</th>
                  <th>Price</th>
                  <th>Work's status</th>
                  <th>Action</th>
              </tr>
          </thead>
          <tbody>
              <% if !@works.nil?%>
                <%  @works.each_with_index do |work, index| %> 
                  <tr>
                      <td><%= index+1 %> </td>
                      <td><%= work.user.fullname%> </td>
                      <td><%= work.name %></td>
                      <td>
                          <% work.categories.each do |category| %>
                            <% if @categories.include? category  %>
                              <%=  link_to category.name, 'javascript:;',class: "btn btn-primary" %>
                              <% else %>
                                <%=  link_to category.name, 'javascript:;', class: "btn btn-danger" %>
                                <%  end %>
                              <% end %>
                          </td>
                          <td><%= work.price %> $</td>
                          <td>
                              <%if work.status == 0%>
                                Waiting
                              <%else%>
                                Delay
                              <%end%>
                          </td>
                          <td>
                              <%= link_to 'View detail', work_path(work), class: "btn btn-default"  %>
                            </td>
                        </tr>
                      <% end %>
                    <%  end%>
                </tbody>
            </table>
        </div>
        <script>
          $('input:checkbox[name="category_ids[]"]').change(
                  function () {
                      var arr = new Array();
                      $('input:checkbox[name="category_ids[]"]').each(function () {
                          if ($(this).is(':checked')) {
                              arr.push($(this).val());
                          }
                      });
                      $.ajax({
                          url: '/search_works',
                          type: 'POST',
                          data: {category_ids: arr},
                          success: function (work) {
                              $("#results").html(work)
                          },
                          error: function () {
                              alert("error");
                          }
                      });
                  });
        </script>

app/views/search_works/search_category.js.erb
$('#result').html('<%= @category.name%>');