config/routes.rb
Rails.application.routes.draw do
  resources :search_images
  get 'categories/index'

  get 'category/index'

  get 'take-test/:id', to:'take_test#index'
  post 'take-test/:id', to:'take_test#create'
  
  get 'joiners/new'

  # get 'joiners/edit'
  get 'joiners/delete'
  get ':id/review_freelancers/new', to: 'review_freelancers#new'
  post ':id/review_freelancers', to: 'review_freelancers#create'

  #  get 'works', to: 'works#index'
  #  get '/works/new', to: 'works#new'
  #  post '/works/new', to: 'works#create'
  #  delete '/works/delete', to: 'works#destroy'
  #  get 'works/edit'
  
  get 'search_works/index'
  get 'search_works', to: 'search_works#index'
  post 'search_works', to: 'search_works#advance'
  
  get 'sessions/new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  root 'static_pages#home'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  get '/edit/:id', to: 'users#edit'
  resources :users
  resources :works
  resources :joiners
  resources :categories
  resources :review_freelancers
#  resources :take
end

app/models/joiner.rb
class Joiner < ApplicationRecord
  belongs_to :user
  belongs_to :work
  has_many :categories, through: :work, through: :user
  has_many :review_freelancer
end

app/controllers/joiners_controller.rb
class JoinersController < ApplicationController
  
  def index
    @user = current_user
    if @user.nil?
      flash[:danger] = "Please login"
      redirect_to login_path
    else
      if @user[:role_id] == 1
        @works = Work.left_outer_joins(:categories).joins(:joiners, :user).where(joiners:{user_id: @user[:id]}).distinct.order("status")
        #        @joiner = Joiner.joins(:work, :user).where()
      else
        flash[:warning] = "You don't have permission"
      end
    end
  end
  
  def create
    @joiner = Joiner.new(joiner_params)
    @joiner.status = 0
    check = Joiner.where(user_id: @joiner.user_id, work_id: @joiner.work_id)
    if check.empty?
      if @joiner.save
        flash[:success] = "Success!"
        @customer = User.joins(:works).where(works:{id: @joiner.work_id}).distinct.first
        NotifierMailer.send_join_to_customer(current_user, @customer)
        redirect_to joiners_path
      else
        flash[:danger] = "Fail!"
        render 'joiners/new'
      end
    else
      flash[:danger] = "You have joined in this work!"
      redirect_to joiners_path
    end
  end

  def update
    @joiner = Joiner.find(params[:id])
    if @joiner.status == 0
      @joiner.status = 1
    else
      @joiner.status = 0
    end
    if @joiner.update_attributes(joiner_params)
      flash[:success] = "Success!"
      redirect_to @joiner.work
    else
      render 'edit'
    end
  end

  def destroy
    @joiner = Joiner.find(params[:id])
    work = Work.joins(:joiners).where(joiners:{id: params[:id]}).first
    if work.status > 0 and @joiner.status == 1
      work[:status] = 4
      work.save;
    end
    @joiner.destroy
    redirect_to work_path(@joiner.work)
  end
  
  private

  def joiner_params
    params.require(:joiner).permit(:user_id, :work_id)
  end
end

app/helpers/joiners_helper.rb
module JoinersHelper
end

app/views/joiners/index.html.erb
<% provide(:title, 'List of joined works') %>
<% unless @works.nil? %>
  <h1>List of projects</h1>
  <table class="table table-border table-hover">
      <thead>
          <tr>
              <th>#</th>
              <th>Work's name</th> 
              <th>Skill Require</th>
              <th>Price</th>
              <th>Work's status</th>
              <th>My status</th>
              <th>Options</th>
          </tr>
      </thead>
      <tbody>
          <% @works.each_with_index do |work, index|  %>
            <tr>
                <td><%= index + 1 %></td>
                <td><%= link_to work.name, work_path(work) %></td>
                <td><% work.categories.each do |category| %>
                      <%=  link_to category.name, 'javascript:;',class: "btn btn-default" %>
                      <%  end %>
                  </td>
                  <td><%= work.price %></td>
                  <td><% if work.status == 1 %>
                        <%= "Started" %>
                      <% elsif work.status == 0 %>
                        <%= "Waiting" %>
                      <% elsif work.status == 2 %>
                        <%= "Done" %>
                       <% elsif work.status == 4 %>
                        <%= "Delay" %>
                      <% end %>
                  </td>
                  <td>
                      <% if work.joiners[0].status == 0 %>
                        <%= "Waiting" %>
                      <% elsif work.joiners[0].status == 1 %>
                        <%= "Accepted" %>
                      <% end %>
                  </td>
                  <td>
                      <%= form_for(work.joiners[0], url: joiner_path(work.joiners[0]), html: {method: "Delete"}) do |d|  %>
                        <%= d.hidden_field :joiner_id, :value =>work.joiners[0].id %>
                        <%#= d.hidden_field :work_id, :values =>work.id %>
                        <%= d.submit "Out", class: "" %>
                        <% end %>
                    </td>
                  <% end %>
          </tbody>
      </table>
    <% end %>

app/views/joiners/new.html.erb
<%unless @work.nil?%>
  <% provide(:title, @work.name) %>
  <div class="row">
      <h3>Work 's detail</h3>
      <table class="table table-hover">
          <tr>
              <td class="active col-md-4">Name</td>
              <td> <%= @work.name %></td>
          </tr>
          <tr>
              <td class="active col-md-4">Customer's name</td>
              <td> <%= link_to @work.user.fullname, user_path(@work.user) %></td>
          </tr>
          <tr>
              <td class="active">Skill Require</td>
              <td> 
                  <% @work.categories.each do |category| %>
                    <%= label_tag '',  category.name , class: 'btn btn-default'%>
                    <%  end %>
                </td>
            </tr>
            <tr>
                <td class="active">Description</td>
                <td> <%= @work.description %></td>
            </tr>
            <tr>
                <td class="active">Price</td>
                <td> <%= @work.price %></td>
            </tr>
            <tr>
                <td colspan="2">
                    <%= form_for(@joiner, url: joiners_path) do |f|  %>
                      <%= f.hidden_field :work_id, :value =>@work.id %>
                      <%= f.hidden_field :user_id, :value =>current_user[:id] %>
                      <%= f.submit "Join work", class: "btn btn-primary col-md-3" %>
                      <% end %>
                  </td>
              </tr>
          </table>

      </div>

    <%else%>
      <h3>Nothing</h3>
    <%end%>